### ISSUE TITLE
Transmit `beingDragged` state of map and tokens over cable

### ISSUE THREAD

**Issue by jdbann** [tableparty/table#38]
Currently, the `beingDragged` state is only known to the user dragging the map. If we can keep this updated across browsers in real-time then it opens up the possibility of adding CSS transitions.

The following CSS adds a nice zoom in/out animation. However, without the `beingDragged` state, other sessions will see the movement of the map and the token smoothed out by the transitions.

```css
.current-map {
  transition-property: background-size background-position;
  transition-duration: 0.5s;

  &[data-being-dragged] {
    transition: none;
  }
}

.current-map__token-container {
  transition-property: left top;
  transition-duration: .5s;
}

.current-map[data-being-dragged] {
  .current-map__token-container {
    transition: none;
  }
}

.token {
  transition-property: left top margin-left margin-top;
  transition-duration: .5s;

  &[data-being-dragged] {
    transition: none;
  }
}

.token__image {
  transition-property: border-width height width;
  transition-duration: .5s;
}
```
